version: "3.0"

services: 
    apache:
        build: .
        ports:
            - 80:80
        volumes: 
            - .:/var/www/html

    mysql:
        image: mysql:5.7
        restart: always
        environment: 
            MYSQL_DATABASE: 'db'
            MYSQL_USER: 'diego'
            MYSQL_PASSWORD: 123456
            MYSQL_ROOT_PASSWORD: 123456
        ports: 
            - 3306:3306
        volumes: 
            - /home/diego/Documents/experiencia/clean-archtecture/mysql:/var/lib/mysql
        expose: 
            - 3306
